### ISSUE TITLE
tensorrt结果和torch是否一致

### ISSUE THREAD

**Issue by Yangfan-96** [zonghaofan/dbnet_torch#1]
你好，tensorrt模型后和torch模型的结果是否一致呢，不一致的话差别有多大呢

**Comment by fanpeace** [comment]
我测过几十张，会有一点点差别，但是不影响使用。



---原始邮件---
发件人: "Yangfan-study"<notifications@github.com&gt;
发送时间: 2020年12月8日(周二) 下午5:30
收件人: "zonghaofan/dbnet_torch"<dbnet_torch@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zonghaofan/dbnet_torch] tensorrt结果和torch是否一致 (#1)




 
你好，tensorrt模型后和torch模型的结果是否一致呢，不一致的话差别有多大呢

**Comment by Yangfan-96** [comment]
我用torch1.3 Trt7.0转opset_version=11的模型会失败，转opset_version=9的模型中间使用一次onnx-sim能成功转换成trt，但是结果差距有点大，我试一下你的环境，谢谢
